version: "3"

services:
    pad:
        image: ubuntu
        container_name: pad
        tty: true
        cap_add:
                - ALL
        sysctls:
                - net.ipv4.conf.all.accept_redirects=1
        privileged: true
        networks:
            net-1.0:
                ipv4_address: 192.168.1.2
        command: sh -c "
                      apt update &&
                      apt install -y iproute2 &&
                      apt install -y iputils-ping &&
                      apt install -y net-tools &&
                      apt install -y nmap &&
                      ip route del default &&
                      ip route add default via 192.168.1.5 &&
                      tail -f /dev/null
         "
    host1:
        image: ubuntu
        container_name: host1
        tty: true
        cap_add:
                - ALL
        sysctls:
                - net.ipv4.conf.all.accept_redirects=1
        privileged: true
        networks:
            net-1.0:
                ipv4_address: 192.168.1.3
        command: sh -c "
                      apt update &&
                      apt install -y iproute2 &&
                      apt install -y iputils-ping &&
                      apt install -y net-tools &&
                      apt install -y nmap &&
                      ip route del default &&
                      ip route add default via 192.168.1.5 &&                      
                      tail -f /dev/null
                 "
    

    host2:
        image: ubuntu
        container_name: host2
        tty: true
        cap_add:
                - ALL
        sysctls:
                - net.ipv4.conf.all.accept_redirects=1
        privileged: true
        networks:
            net-2.0:
                ipv4_address: 192.168.2.2
        command: sh -c "
                      apt update &&
                      apt install -y iproute2 &&
                      apt install -y iputils-ping &&
                      apt install -y net-tools &&
                      apt install -y nmap &&
                      ip route del default &&
                      ip route add default via 192.168.2.5 &&
                      tail -f /dev/null
                 "
    host3:
        image: ubuntu
        container_name: host3
        tty: true
        cap_add:
                - ALL
        privileged: true
        sysctls:
                - net.ipv4.conf.all.accept_redirects=1
        networks:
            net-2.0:
                ipv4_address: 192.168.2.3
        command: sh -c "
                      apt update &&
                      apt install -y iproute2 &&
                      apt install -y iputils-ping &&
                      apt install -y net-tools &&
                      apt install -y nmap &&
                      ip route del default &&
                      ip route add default via 192.168.2.5 &&
                      tail -f /dev/null
                 "
    host4:
        image: ubuntu
        container_name: host4
        tty: true
        cap_add:
                - ALL
        privileged: true
        sysctls:
                - net.ipv4.conf.all.accept_redirects=1
        networks:
            net-2.0:
                ipv4_address: 192.168.2.4
        command: sh -c "
                      apt update &&
                      apt install -y iproute2 &&
                      apt install -y iputils-ping &&
                      apt install -y net-tools &&
                      apt install -y nmap &&
                      ip route del default &&
                      ip route add default via 192.168.2.5 &&
                      tail -f /dev/null
                 "

    print-server:
        image: ubuntu
        container_name: print-server
        tty: true
        cap_add:
                - ALL
        privileged: true
        sysctls:
                - net.ipv4.conf.all.accept_redirects=1
        networks:
            net-3.0:
                ipv4_address: 192.168.3.2
        command: sh -c "
                      apt update &&
                      apt install -y iproute2 &&
                      apt install -y iputils-ping &&
                      apt install -y net-tools &&
                      apt install -y nmap &&
                      ip route del default &&
                      ip route add default via 192.168.3.5 &&
                      tail -f /dev/null
                 "
    file-server:
        image: ubuntu
        container_name: file-server
        tty: true
        cap_add:
                - ALL
        privileged: true
        sysctls:
                - net.ipv4.conf.all.accept_redirects=1
        networks:
            net-3.0:
                ipv4_address: 192.168.3.3
        command: sh -c "
                      apt update &&
                      apt install -y iproute2 &&
                      apt install -y iputils-ping &&
                      apt install -y net-tools &&
                      apt install -y nmap &&
                      ip route del default &&
                      ip route add default via 192.168.3.5 &&
                      tail -f /dev/null
                 "
    database-server:
        image: ubuntu
        container_name: database-server
        tty: true
        cap_add:
                - ALL
        privileged: true
        sysctls:
                - net.ipv4.conf.all.accept_redirects=1
        networks:
            net-3.0:
                ipv4_address: 192.168.3.4
        command: sh -c "
                      apt update &&
                      apt install -y iproute2 &&
                      apt install -y iputils-ping &&
                      apt install -y net-tools &&
                      apt install -y nmap &&
                      ip route del default &&
                      ip route add default via 192.168.3.5 &&
                      tail -f /dev/null
                 "
    web-server:
        image: ubuntu
        container_name: web-server
        tty: true
        cap_add:
                - ALL
        privileged: true
        sysctls:
                - net.ipv4.conf.all.accept_redirects=1
        networks:
            net-dmz:
                ipv4_address: 192.168.4.2
        command: sh -c "
                      apt update &&
                      apt install -y iproute2 &&
                      apt install -y iputils-ping &&
                      apt install -y net-tools &&
                      apt install -y nmap &&
                      ip route del default &&
                      ip route add default via 192.168.4.5 &&
                      tail -f /dev/null
                 "
    wazuh-server:
        image: ubuntu
        container_name: wazuh-server
        tty: true
        cap_add:
                - ALL
        privileged: true
        sysctls:
                - net.ipv4.conf.all.accept_redirects=1
        networks:
            net-wazuh:
                ipv4_address: 192.168.20.2
        command: sh -c "
                      tail -f /dev/null
                 "

    switch:
        image: ubuntu
        container_name: switch
        tty: true
        cap_add:
                - ALL
        sysctls:
                - net.ipv4.ip_forward=1
    
        networks:
            net-router: 
                ipv4_address: 192.168.5.5
            net-1.0:
                ipv4_address: 192.168.1.5
            net-2.0:
                ipv4_address: 192.168.2.5
            net-3.0:
                ipv4_address: 192.168.3.5
            net-dmz:
                ipv4_address: 192.168.4.5
            net-wazuh:
                ipv4_address: 192.168.20.5
        command: sh -c "
                      apt update &&
                      apt install -y iproute2 &&
                      apt install -y iputils-ping &&
                      apt install -y net-tools &&
                      ip route del default &&
                      ip route add default via 192.168.5.2 &&
                      tail -f /dev/null
                "
    
    router:
        image: ubuntu
        container_name: router
        tty: true
        cap_add:
                - ALL
        sysctls:
                - net.ipv4.ip_forward=1

        networks:
            internet:
                ipv4_address: 192.168.10.2
            net-router: 
                ipv4_address: 192.168.5.2
        command: sh -c "
                      apt update &&
                      apt install -y iproute2 &&
                      apt install -y iputils-ping &&
                      apt install -y net-tools &&
                      apt install -y traceroute &&
                      ip route add 192.168.1.0/24 via 192.168.5.5 &&
                      ip route add 192.168.2.0/24 via 192.168.5.5 &&
                      ip route add 192.168.3.0/24 via 192.168.5.5 &&
                      ip route add 192.168.4.0/24 via 192.168.5.5 &&
                      tail -f /dev/null
                "
    
    attacker:
        image: ubuntu
        container_name: attacker
        tty: true
        cap_add:
                - ALL
        sysctls:
                - net.ipv4.ip_forward=1
        networks:
            internet:
                ipv4_address: 192.168.10.10
        command: sh -c "
                      apt update &&
                      apt install -y iproute2 &&
                      apt install -y iputils-ping &&
                      apt install -y net-tools &&
                      apt install -y nmap &&
                      apt install -y traceroute &&
                      ip route del default &&
                      route add default gw 192.168.10.2 &&
                      tail -f /dev/null
                "       

networks:
    net-1.0:
        name: net-1.0
        ipam:
            config:
                - subnet: 192.168.1.0/24
    net-2.0:
        name: net-2.0
        ipam:
            config:
                - subnet: 192.168.2.0/24
    net-3.0:
        name: net-3.0
        ipam:
            config:
                - subnet: 192.168.3.0/24
    net-dmz:
        name: net-dmz
        ipam:
            config:
                - subnet: 192.168.4.0/24
    net-router:
        name: net-router
        ipam: 
            config:
                - subnet: 192.168.5.0/24
    net-wazuh:
        name: net-wazuh
        ipam:
            config:
                - subnet: 192.168.20.0/24
    internet:
        name: internet
        ipam: 
            config:
                - subnet: 192.168.10.0/24